# Generated by Django 2.2.5 on 2019-11-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0003_attachment_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='chat_id',
            new_name='chat',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='message_id',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='user_id',
            new_name='user',
        ),
    ]
