# Generated by Django 2.2.5 on 2019-11-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0005_auto_20191113_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='key',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attach_type',
            field=models.CharField(max_length=32, verbose_name='Тип'),
        ),
    ]
