# Generated by Django 2.2.5 on 2019-11-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0008_auto_20191120_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='content',
            field=models.FileField(null=True, upload_to='attachments/'),
        ),
    ]
