# Generated by Django 2.2.5 on 2019-11-06 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('chats', '0001_initial'),
        ('dialogs', '0002_message_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('new_messages', models.TextField()),
                ('chat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.Chat')),
                ('last_read_message_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dialogs.Message')),
            ],
        ),
    ]
