# Generated by Django 2.2.5 on 2019-11-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='chat_id',
            new_name='chat',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='last_read_message_id',
            new_name='last_read_message',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='user_id',
            new_name='user',
        ),
    ]
