# Generated by Django 2.2.5 on 2019-11-13 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20191112_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterField(
            model_name='member',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.Chat', verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_read_message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dialogs.Message', verbose_name='Последнее прочтённое сообщение'),
        ),
        migrations.AlterField(
            model_name='member',
            name='new_messages',
            field=models.TextField(verbose_name='Новые сообщения'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
