# Generated by Django 2.2.5 on 2019-11-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20191113_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.ImageField(null=True, upload_to='member_avatars/'),
        ),
    ]
