# Generated by Django 2.2.5 on 2019-11-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_group_chat', models.BooleanField(verbose_name='Group chat status')),
                ('topic', models.CharField(max_length=32, verbose_name='Topic')),
                ('last_message', models.TextField(verbose_name='Last Message')),
            ],
        ),
    ]
