# Generated by Django 2.2.5 on 2019-11-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AlterField(
            model_name='chat',
            name='is_group_chat',
            field=models.BooleanField(verbose_name='Групповой чат'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.TextField(verbose_name='Последнее сообщение'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='topic',
            field=models.CharField(max_length=32, verbose_name='Топик'),
        ),
    ]
